services:
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    command: redis-server --requirepass redis

  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: